name: Continuous Integration

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  NODE_VERSION: '20'

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Install CDK dependencies
        run: cd infrastructure/cdk && npm ci

      - name: Install frontend dependencies  
        run: cd frontend && npm ci

      - name: Build project
        run: npm run build

      - name: Run CDK tests
        run: cd infrastructure/cdk && npm test

      - name: Run frontend tests
        run: cd frontend && npm test -- --passWithNoTests --watchAll=false --coverage

      - name: Security audit (root)
        run: npm audit --audit-level=high --omit=dev
        continue-on-error: true

      - name: Security audit (frontend)
        run: cd frontend && npm audit --audit-level=high --omit=dev
        continue-on-error: true

      - name: CDK synthesis check
        run: cd infrastructure/cdk && npx cdk synth --quiet

  build:
    name: Build Assets
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd infrastructure/cdk && npm ci
          cd ../../frontend && npm ci

      - name: Build frontend for production
        run: cd frontend && npm run build

      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build/
          retention-days: 7

      - name: Build and synthesize CDK
        run: npm run build

      - name: Upload CDK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cdk-build
          path: infrastructure/cdk/cdk.out/
          retention-days: 7