name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

env:
  NODE_VERSION: '20'
  AWS_REGION: 'us-west-2'

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    # Only run on main branch pushes or manual dispatch
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    
    environment: 
      name: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: |
          npm ci
          cd infrastructure/cdk && npm ci
          cd ../../frontend && npm ci

      - name: Build frontend for production
        run: cd frontend && npm run build

      - name: Build CDK
        run: npm run build

      - name: Deploy CDK stack
        run: |
          cd infrastructure/cdk
          npx cdk deploy --require-approval never --context env=${{ github.event.inputs.environment || 'production' }}

      - name: Run post-deployment smoke tests
        run: |
          # Basic health check - will be enhanced with actual API endpoints
          echo "Deployment completed successfully"
          echo "Stack outputs:"
          cd infrastructure/cdk
          npx cdk ls --long

      - name: Notify deployment success
        if: success()
        run: |
          echo "✅ Deployment to ${{ github.event.inputs.environment || 'production' }} successful"
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"

      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ Deployment to ${{ github.event.inputs.environment || 'production' }} failed"
          echo "Check the logs above for details"
          exit 1